extjs/build/classic/locale /usr/share/javascript/extjs
extjs/build/classic/theme-crisp /usr/share/javascript/extjs
extjs/build/ext-all-debug.js /usr/share/javascript/extjs
extjs/build/ext-all.js /usr/share/javascript/extjs
extjs/build/packages/charts/classic/charts-debug.js /usr/share/javascript/extjs
extjs/build/packages/charts/classic/charts.js /usr/share/javascript/extjs
extjs/build/packages/charts/classic/crisp /usr/share/javascript/extjs
